<?php
/** @var \Laminas\Mvc\Plugin\FlashMessenger\View\Helper\FlashMessenger $flash */
$flash = $this->flashMessenger();

$flash->setMessageOpenFormat(
    '<div%s>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <ul class="list-unstyled">
        <li>'
)->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>'); ?>

<div class="row justify-content-center">
    <div class="col-12 col-md-6">
        <?= $flash->render('info', ['alert auto-remove', 'alert-dismissible', 'alert-info fade show']); ?>
        <?= $flash->render('error', ['alert auto-remove', 'alert-dismissible', 'alert-danger fade show']); ?>
        <?= $flash->render('default', ['alert auto-remove', 'alert-dismissible', 'alert-warning fade show']); ?>
        <?= $flash->render('success', ['alert auto-remove', 'alert-dismissible', 'alert-success fade show']); ?>
    </div>
</div>