<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 */

/** @var \Organisation\Form\DepartmentForm $form */
$form = $this->form;
$form->setAttribute('action', $this->url('employees/save'));
$form->prepare();
?>

<div class="mt-5 row justify-content-center align-items-center">
    <div class="col-12 col-md-6">
        <div class="mb-3">

        </div>

        <h3><?= $this->translate('employee_form'); ?></h3>
        <?= $this->form()->openTag($form); ?>
        <div class="mb-3">
            <div class="text-danger">
                <?=$this->formElementErrors($form->get('last_name')); ?>
            </div>
            <?= $this->formText($form->get('last_name')); ?>
            <?= $this->formLabel($form->get('last_name')); ?>
        </div>

        <div class="mb-3">
            <div class="text-danger">
                <?=$this->formElementErrors($form->get('first_name')); ?>
            </div>
            <?= $this->formText($form->get('first_name')); ?>
            <?= $this->formLabel($form->get('first_name')); ?>
        </div>

        <div class="mb-3">
            <div class="text-danger">
                <?=$this->formElementErrors($form->get('middle_name')); ?>
            </div>
            <?= $this->formText($form->get('middle_name')); ?>
            <?= $this->formLabel($form->get('middle_name')); ?>
        </div>

        <div class="mb-3">
            <div class="text-danger">
                <?=$this->formElementErrors($form->get('birth_date')); ?>
            </div>
            <?= $this->formDateSelect($form->get('birth_date')); ?>
            <?= $this->formLabel($form->get('birth_date')); ?>
        </div>

        <div class="mb-3">
            <div class="text-danger">
                <?=$this->formElementErrors($form->get('birth_place')); ?>
            </div>
            <?= $this->formText($form->get('birth_place')); ?>
            <?= $this->formLabel($form->get('birth_place')); ?>
        </div>

        <div class="mb-3">
            <?= $this->formHidden($form->get('employee')); ?>
            <?= $this->formHidden($form->get('csrf')); ?>
            <div class="text-danger">
                <?= $this->formElementErrors($form->get('csrf')); ?>
            </div>

            <div class="d-flex justify-content-start align-items-center">
                <?= $this->formSubmit($form->get('save')); ?>
                <a class="btn btn-outline-dark ms-2" href="<?=$this->url('employees'); ?>">
                    <?= $this->translate('to_employees_list'); ?>
                </a>
            </div>
        </div>
    </div>
</div>



