<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var array|\Organisation\Model\Department[] $departments
 */

?>
<div class="row justify-content-center">
    <div class="col-12 col-md-6">
        <div class="mb-3">
            <h2><?= $this->translate('department_list'); ?></h2>
        </div>

        <div class="table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th><?= $this->translate('id'); ?></th>
                    <th><?= $this->translate('name'); ?></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php
                foreach ($departments as $department) { ?>
                    <tr>
                        <td class="align-middle"><?= $department->id; ?></td>
                        <td class="align-middle"><?= $department->name; ?></td>
                        <td class="align-middle">
                            <a class="btn btn-warning btn-sm" href="/departments/form/<?=$department->id; ?>">
                                <?= $this->translate('edit'); ?>
                            </a>
                        </td>
                    </tr>
                <?php }?>
                </tbody>
            </table>
        </div>
    </div>
</div>
