<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="d-flex justify-content-center align-items-center" style="height: 100vh">
    <div class="d-block">
        <h3>Organisation</h3>
        <div class="d-flex justify-content-between">
            <a href="/departments"><?=$this->translate('departments')?></a>
            <a href="/employees"><?=$this->translate('employees')?></a>
        </div>
    </div>
</div>
